apiVersion: v1
kind: Pod
metadata:
    name: mypod
    labels:
        type: app
spec:
    containers:
        - name: webserver
          image: image_tag
          ports:
            - containerPort: 80
